export const CartActionsTypes ={
    ADD_SEAT_CART    : 'ADD_SEAT_CART',
    REMOVE_SEAT_CART : 'REMOVE_SEAT_CART',
    CLEAR_SEATS_CART : 'CLEAR_SEATS_CART',
    UPDATE_PRICE_SEAT : 'UPDATE_PRICE_SEAT'
}