export const StageActionsTypes ={
    SET_STATE_SEAT :'SET_STATE_SEAT',
    SET_CLOCK_TIME :'SET_CLOCK_TIME',
    SET_SPEAKER    :'SET_SPEAKER',
    SET_COURSE     :'SET_COURSE',
    SET_PROCESING_SEAT  :'SET_PROCESING_SEAT',
    SET_OPTION_SIGNIN_SIGNUP  :'SET_OPTION_SIGNIN_SIGNUP'
}